blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity, \
    CreateBlogList
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog_list/', cache_page(60)(BlogListView.as_view()), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(),  name='detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
    path('toggle_activity', CreateBlogList, name='toggle')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sendler.urls', namespace='sendler')),
    path('contacts/', include("sendler.urls")),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sendler/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from sendler.apps import SendlerConfig
from sendler.views import IndexView, ContactsView, ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, \
    ClientDeleteView, MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    MailSettingsListView, MailSettingsDetailView, MailSettingsCreateView, MailSettingsUpdateView, \
    MailSettingsDeleteView, LogListView

app_name = SendlerConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contacts/', ContactsView.as_view(), name='contacts'),

    path('client/', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

    path('message/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('mail_settings/', cache_page(60)(MailSettingsListView.as_view()), name='mail_settings_list'),
    path('mail_settings/<int:pk>/', MailSettingsDetailView.as_view(), name='mail_settings_detail'),
    path('mail_settings/create/', MailSettingsCreateView.as_view(), name='mail_settings_create'),
    path('mail_settings/<int:pk>/update/', MailSettingsUpdateView.as_view(), name='mail_settings_update'),
    path('mail_settings/<int:pk>/delete/', MailSettingsDeleteView.as_view(), name='mail_settings_delete'),

    path('log_list/', LogListView.as_view(), name='log_list'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, ProfileView, CustomPasswordReset, UserListView, \
    UserDetailView, UserDeleteView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path("users/", UserListView.as_view(), name="user_list"),
    path("users/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("users/<int:pk>/update", UserUpdateView.as_view(), name="user_update"),
    path("users/<int:pk>/delete", UserDeleteView.as_view(), name="user_delete"),
    path('password_reset/', CustomPasswordReset.as_view(), name='password_reset')

]

sendler/models.py
from django.utils import timezone

from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """Клиент сервиса"""
    first_name = models.CharField(max_length=150, verbose_name='Имя', help_text='Введите имя клиента', **NULLABLE)
    last_name = models.CharField(max_length=150, verbose_name='Фамилия', help_text='Введите фамилию клиента',
                                 **NULLABLE)
    email = models.EmailField(verbose_name='email получателя', help_text='Введите email клиента')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE, help_text='Комментарий')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.last_name} {self.first_name}: {self.email}'

    class Meta:
        verbose_name = 'Получатель'
        verbose_name_plural = 'Получатели'
        ordering = ['first_name', 'email']


class Message(models.Model):
    """Сообщение для рассылки"""
    message_title = models.CharField(max_length=250, verbose_name='тема сообщения', help_text='Тема сообщения')
    message_text = models.TextField(verbose_name='текст сообщения', help_text='Сообщение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    update_at = models.DateTimeField(auto_now=True, verbose_name='дата обновления')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return self.message_title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['message_title']


class MailSettings(models.Model):
    """Настройки Рассылки"""
    CHOICES_PERIODICITY = (
        ('DAILY', 'ежедневно'),
        ('WEEKLY', 'еженедельно'),
        ('MONTHLY', 'ежемесячно'),
    )
    CHOICES_STATUS = (
        ('CREATE', 'создана'),
        ('LAUNCHED', 'запущена'),
        ('COMPLETED', 'завершена'),
    )
    first_time_send = models.DateTimeField(default=timezone.now, verbose_name='дата и время первой отправки рассылки')
    periodicity = models.CharField(max_length=50, default='DAILY', verbose_name='Периодичность рассылки',
                                   choices=CHOICES_PERIODICITY, help_text='Выберете периодичность рассылки')
    status = models.CharField(max_length=50, default='CREATE', verbose_name='статус рассылки', choices=CHOICES_STATUS,
                              help_text='статус рассылки')
    is_active = models.BooleanField(default=True, verbose_name='Активация рассылки')
    clients = models.ManyToManyField(Client, verbose_name='клиенты', help_text='выберете клиентов для рассылки',
                                     related_name='mailings')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение',
                                help_text='выберете сообщение', related_name='mailings')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return f'{self.status}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'

        permissions = [
            ('can_view_mail_settings', 'Может просматривать рассылки'),
            ('can_change_mail_settings', 'Может отключать рассылки'),
            ('can_view_user', 'Может просматривать пользователей'),
            ('can_block_user', 'Может блокировать пользователей')
        ]


class Log(models.Model):
    """Логи рассылки"""
    STATUS_SEND = (
        ('SUCCESSFUL', 'успешно'),
        ('NOT_SUCCESSFUL', 'не успешно'),
    )
    date_last_attempt = models.DateTimeField(auto_now=True, verbose_name=' дата и время последней попытки')
    attempt_status = models.CharField(max_length=50, choices=STATUS_SEND, verbose_name='статус попытки')
    server_response = models.TextField(verbose_name='ответ сервера', **NULLABLE)
    mailing = models.ForeignKey(MailSettings, on_delete=models.CASCADE, verbose_name='рассылка', related_name='logs')

    def __str__(self):
        return f'{self.date_last_attempt} {self.attempt_status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

sendler/forms.py
from django.forms import ModelForm, BooleanField, DateTimeInput

from sendler.models import Client, Message, MailSettings, Log


class StyleFormMixin:
    """Миксин для стилизации формы"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, ModelForm):
    """Форма редактирования клиента"""

    class Meta:
        model = Client
        fields = ('email', 'first_name', 'last_name', 'comment')


class MessageForm(StyleFormMixin, ModelForm):
    """Форма редактирования сообщения"""

    class Meta:
        model = Message
        fields = ('message_title', 'message_text')


class MailSettingsForm(StyleFormMixin, ModelForm):
    """Форма редактирования настройки рассылки"""

    class Meta:
        model = MailSettings
        fields = '__all__'
        widgets = {
            'first_time_send': DateTimeInput(format='%Y-%m-%d %H:%M', attrs={'type': 'datetime-local'})
        }


class LogView(StyleFormMixin, ModelForm):
    """Форма редактирования попытки рассылки"""

    class Meta:
        model = Log
        fields = ('attempt_status',)


class MailSettingsModeratorForm(StyleFormMixin, ModelForm):
    """Форма редактирования настройки рассылки для модераторов"""

    class Meta:
        model = MailSettings
        fields = ('is_active',)

sendler/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import Blog
from sendler.forms import ClientForm, MessageForm, MailSettingsForm, MailSettingsModeratorForm
from sendler.models import MailSettings, Client, Message, Log


class IndexView(TemplateView):
    """Контроллер главной страницы"""
    template_name = 'sendler/index.html'
    extra_context = {'title': 'Главная страница'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing_count'] = MailSettings.objects.count()
        context['active_mailing'] = MailSettings.objects.filter(status='CREATE').count()
        context['unique_clients'] = Client.objects.values('email').distinct().count()
        all_posts = list(Blog.objects.filter(is_published=True))
        context['random_posts'] = Blog.objects.all().order_by('?')[:3]
        return context


class ContactsView(View):
    """Контроллер страницы контактов"""

    def get(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f' {name} ({phone}): {message})')
        context = {
            'title': 'Контакты'
        }
        return render(request, 'sendler/contacts.html', context)


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('sendler:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    """Контроллер списка клиентов"""
    model = Client

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            return Client.objects.all()
        else:
            return Client.objects.filter(owner=user)


class ClientDetailView(LoginRequiredMixin, DetailView):
    """Контроллер просмотра клиента"""
    model = Client

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        return context_data


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер редактирования клиента"""
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse_lazy('sendler:client_detail', args=[self.kwargs.get('pk')])


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """Контроллер удаления клиента"""
    model = Client
    success_url = reverse_lazy('sendler:client_list')


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания сообщения"""

    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('sendler:message_list')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    """Контроллер списка сообщений"""

    model = Message

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            return Message.objects.all()
        else:
            return Message.objects.filter(owner=user)


class MessageDetailView(LoginRequiredMixin, DetailView):
    """Контроллер детального просмотра сообщения"""

    model = Message

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        return context_data


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер редактирования сообщения"""

    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse_lazy('sendler:message_detail', args=[self.kwargs.get('pk')])


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """Контроллер удаления сообщения"""

    model = Message
    success_url = reverse_lazy('sendler:message_list')


class MailSettingsCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания настройки рассылки"""

    model = MailSettings
    form_class = MailSettingsForm
    success_url = reverse_lazy('sendler:mail_settings_list')

    def form_valid(self, form):
        mail_settings = form.save()
        user = self.request.user
        mail_settings.owner = user
        mail_settings.save()
        return super().form_valid(form)


class MailSettingsListView(LoginRequiredMixin, ListView):
    """Контроллер списка настроек рассылки"""

    model = MailSettings
    template_name = 'mailsettings_list.html.html'

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.has_perm('sendler.can_view_mail_settings'):
            return MailSettings.objects.all()
        return MailSettings.objects.filter(owner=user)


class MailSettingsDetailView(LoginRequiredMixin, DetailView):
    """Контроллер детального просмотра настройки рассылки"""

    model = MailSettings

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        return context_data


class MailSettingsUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер редактирования настройки рассылки"""

    model = MailSettings

    form_class = MailSettingsForm

    def get_success_url(self):
        return reverse_lazy('sendler:mail_settings_detail', args=[self.kwargs.get('pk')])

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # Извлекаем аргумент 'user' из kwargs
        super().__init__(*args, **kwargs)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return MailSettingsForm
        if user.has_perm('sendler.can_view_mail_settings') and user.has_perm('sendler.can_change_mail_settings'):
            return MailSettingsModeratorForm
        raise PermissionDenied


class MailSettingsDeleteView(LoginRequiredMixin, DeleteView):
    """Контроллер удаления настройки рассылки"""

    model = MailSettings
    success_url = reverse_lazy('sendler:mail_settings_list')


class LogListView(LoginRequiredMixin, ListView):
    """Контроллер списка попыток рассылки"""

    model = Log
    template_name = 'sendler/log_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['attempts'] = 'Попытки рассылки'
        context['log_list'] = Log.objects.all().order_by('-id')[:10]
        return context

sendler/templates/sendler/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet"
         crossorigin="anonymous">
    <!-- Favicons -->

    <meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }


    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
</head>
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4>Меню</h4>

            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4>Навигация</h4>
                <ul class="list-unstyled">
                    <li><a href="{% url 'sendler:index' %}" class="text-blue">Главная</a></li>
                    <li><a href="{% url 'sendler:contacts' %}" class="text-blue">Контакты</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'users:logout' %}" class="text-blue">Выход</a></li>
                    <li><a href="{% url 'users:profile' %}" class="text-blue">Профиль</a></li>
                    {% else %}
                    <li><a href="{% url 'users:login' %}" class="text-blue">Вход</a></li>
                    <li><a href="{% url 'users:register' %}" class="text-blue">Регистрация</a></li>
                    {% endif %}

                    <li><a href="{% url 'blog:list' %}" class="text-blue">Блог</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">

        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>
<body>

<header>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

        </div>
    </nav>
</header>


<main>

    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true"
                    aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <rect width="100%" height="100%" fill="#777"/>
                </svg>

                <div class="container">
                    <div class="carousel-caption text-start">
                        <h1>Всё необходимое для email-рассылок</h1>
                        <h2>С нашим сервисом вы сможете максимально эффективно использовать отправку писем</h2>
                        <hr>
                        {% if user.is_authenticated %}
                        <a class="btn btn-lg btn-primary" href="{% url 'sendler:mail_settings_create' %}">Создать
                            рассылку</a>
                        {% else %}
                        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}">Регистрация</a>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <rect width="100%" height="100%" fill="#777"/>
                </svg>

                <div class="container">
                    <div class="carousel-caption">
                        <h1>Зарегистрируйтесть для пользования сервисом </h1>
                        <h2>Отправляйте рассылки, автоматизируйте маркетинг и увеличивайте продажи</h2>
                        <hr>
                        {% if user.is_authenticated %}
                        <a class="btn btn-lg btn-primary" href="{% url 'sendler:client_create' %}">Создать клиента</a>
                        {% else %}
                        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}">Стать пользователем</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg"
                     aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
                    <rect width="100%" height="100%" fill="#777"/>
                </svg>

                <div class="container">
                    <div class="carousel-caption text-end">
                        <h1>Блог - это мощный инструмент продвижения бизнеса </h1>
                        <h2>В нашем блоге можно прочитать статьи из мира IT</h2>
                        <hr>
                        <a class="btn btn-lg btn-primary" href="{% url 'blog:list' %}">Читать блог</a>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-4">
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#777"/>
                    <text x="50%" y="50%" fill="#777" dy=".3em">140x140</text>
                </svg>

                <h2>Рассылки</h2>
                <h4>Количество рассылок: {{ mailing_count }}</h4>
                <h4>Количество активных рассылок: {{ active_mailing }}</h4>
                <p><a class="btn btn-secondary" href="{% url 'sendler:mail_settings_list' %}">Подробнее &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#777"/>
                    <text x="50%" y="50%" fill="#777" dy=".3em">140x140</text>
                </svg>

                <h2>Сообщения для рассылок</h2>
                <h4>Просмотр и создание сообщений для рассылки</h4>
                <p><a class="btn btn-secondary" href="{% url 'sendler:message_list' %}">Подробнее &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#777"/>
                    <text x="50%" y="50%" fill="#777" dy=".3em">140x140</text>
                </svg>

                <h2>Клиенты для рассылки</h2>
                <h4>Количество уникальных клиентов для рассылок: {{ unique_clients }}</h4>
                <p><a class="btn btn-secondary" href="{% url 'sendler:client_list' %}">Подробнее &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

<hr class="featurette-divider">

{% for object in random_posts %}
    <div class="row featurette">
        {% if forloop.counter|divisibleby:2 %}
            <div class="col-md-7 order-md-2">
        {% else %}
            <div class="col-md-7">
        {% endif %}
                <h2 class="featurette-heading">{{ object.title }}</h2>
                <p class="lead">{{ object.content|truncatechars:200 }}</p>
                <small class="text-body-secondary">Дата создания: {{ object.created_at }}</small>
                <br>
                <small class="text-body-secondary">Количество просмотров: {{ object.views_count }}</small>
                <br>
                <a class="btn btn-secondary mt-3" href="{% url 'blog:detail' object.pk %}">Читать статью &raquo;</a>
            </div>

            <div class="col-md-5">
                <img src="/media/{{ object.preview }}"  width="500" height="500">
            </div>
    </div>
    <hr class="featurette-divider">
{% endfor %}


        <!-- /END THE FEATURETTES -->

  <!-- /.container -->


    <!-- FOOTER -->
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>&copy; 2024 - {% now "Y" %}</p>
    </footer>
</main>


<script src="{% static 'js/bootstrap.bundle.min.js'%}"

        crossorigin="anonymous"></script>


</body>
</html>

sendler/templates/sendler/mailsettings_confirm_delete.html
{% extends 'sendler/base.html' %}
{% block content %}
<div class="container">
    <h1 class="fw-light">Сервис Email рассылок</h1>
    <hr>
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Подтвердите удаление {{ object.periodicity}}</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-danger">Удалить</button>
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'sendler:mail_settings_list' %}" role="button">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}