blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity, \
    CreateBlogList
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog_list/', cache_page(60)(BlogListView.as_view()), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(),  name='detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
    path('toggle_activity', CreateBlogList, name='toggle')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sendler.urls', namespace='sendler')),
    path('contacts/', include("sendler.urls")),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sendler/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from sendler.apps import SendlerConfig
from sendler.views import IndexView, ContactsView, ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, \
    ClientDeleteView, MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    MailSettingsListView, MailSettingsDetailView, MailSettingsCreateView, MailSettingsUpdateView, \
    MailSettingsDeleteView, LogListView

app_name = SendlerConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contacts/', ContactsView.as_view(), name='contacts'),

    path('client/', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

    path('message/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('mail_settings/', cache_page(60)(MailSettingsListView.as_view()), name='mail_settings_list'),
    path('mail_settings/<int:pk>/', MailSettingsDetailView.as_view(), name='mail_settings_detail'),
    path('mail_settings/create/', MailSettingsCreateView.as_view(), name='mail_settings_create'),
    path('mail_settings/<int:pk>/update/', MailSettingsUpdateView.as_view(), name='mail_settings_update'),
    path('mail_settings/<int:pk>/delete/', MailSettingsDeleteView.as_view(), name='mail_settings_delete'),

    path('log_list/', LogListView.as_view(), name='log_list'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    """Класс модели блога"""
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='контент')
    preview = models.ImageField(upload_to='blog/image', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name='дата создания', **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        permissions = [
            ('can_add_blog', 'Can add blog'),
            ('can_view_blog', 'Can view blog'),
            ('can_change_blog', 'Can change blog'),
            ('can_delete_blog', 'Can delete blog'),
        ]

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.models import Blog


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Контроллер создания статьи"""
    model = Blog
    fields = ('title', 'content', 'preview', 'is_published')
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.can_add_blog'
    extra_context = {'title': 'Создание статьи'}

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogListView(LoginRequiredMixin, ListView):
    """Контроллер просмотра статей"""
    model = Blog
    template_name = 'blog/blog_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        blog = Blog.objects.all()

        context_data['object_list'] = blog
        context_data['title'] = 'Блог'

        return context_data


class BlogDetailView(LoginRequiredMixin, DetailView):
    """Контроллер просмотра статьи"""
    model = Blog
    template_name = 'blog/blog_detail.html'
    extra_context = {'title': 'Просмотр статьи'}

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Контроллер редактирования статьи"""
    model = Blog
    fields = ('title', 'content', 'preview', 'is_published')
    permission_required = 'blog.can_change_blog'
    extra_context = {'title': 'Редактирование статьи'}

    # success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """Контроллер удаления статьи"""
    model = Blog
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.can_delete_blog'
    extra_context = {'title': 'Удаление статьи'}


def toggle_activity(request, pk):
    """Функция переключения активности статьи"""
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:
        blog_item.is_published = True

    blog_item.save()
    return redirect(reverse('blog:list'))


def CreateBlogList(request):
    blog_list = Blog.objects.all()
    context = {
        'object_list': blog_list,

    }

    return render(request, 'blog/toggle.html', context)

blog/templates/blog/blog_confirm_delete.html
{% extends 'sendler/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text"> Действительно хотите удалить? {{ blog.title }}</p>
                    <div class="card-body">

                        {% csrf_token %}
                        <
                        <button type="submit" role="button" tabindex="-1" class="btn btn-danger">
                            Удалить
                        </button>
                        <a class="btn btn-warning" href="{% url 'blog:list' %}" role="button">Отменить</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'sendler/base.html' %}
{% block content %}
{% load my_tags %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card shadow-sm">
            <img src="/media/{{ blog.preview }}"/>
            <h5 class="card-title">{{ object.name }}</h5>
            <div class="card-body">
                <h5 class="card-title">{{ blog.title }}</h5>
                <p class="card-text">{{ blog.content }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a class="btn btn-primary" href="{% url 'blog:list' %}" role="button">Назад</a>
                    </div>
                    <div class="btn-group">
                        {% if perms.blog.can_change_blog and perms.blog.can_delete_blog %}
                        <a class="btn btn-warning" href="{% url 'blog:update' blog.pk %}" role="button">Редактировать</a>
                    <div>

                        <a class="btn btn-danger" href="{% url 'blog:delete' blog.pk %}" role="button">Удалить</a>
                        {% endif %}
                    </div>
                </div>
                <small class="text-body-secondary">Количество просмотров {{ object.views_count }}</small>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'sendler/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}

                            <div class="d-flex justify-content-between align-items-center">
                            <button type="submit" role="button" tabindex="-1" class="btn btn-primary">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                                </button>
                                </a>
                                <div class="btn-group">
                                    <a class="btn btn-warning" href="{% url 'blog:list' %}" role="button">Назад</a>

                        </div>
                    </div>
                </div>
        </div>
        </form>
    </div>
</div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'sendler/base.html' %}
{% load my_tags %}
{% block content %}
    <a class="btn btn-primary" href="{% url 'sendler:index' %}" role="button">На главную</a>
{% if perms.blog.can_add_blog %}
        <div>
            <a href="{% url 'blog:create' %}" class="btn btn-outline-secondary">Создать статью</a>
        </div>
    {% endif %}
<br>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">


    {% for blog in object_list %}
    <div class="col">
        {% if blog.is_published %}
        <div class="card shadow-sm">
            <div class="card-body">

                <img src="/media/{{ blog.preview }}" width="250" height="300/>


                <small class="text-body-secondary">Дата создания {{ blog.created_at }}</small>
                <small class="text-body-secondary">Количество просмотров {{ blog.views_count }}</small>

                <small class="text-body-secondary">SLUG ({{ blog.slug }})</small>

                <h5 class="card-title">{{ blog.title }} </h5>

                <p class="card-text">{{ blog.content|truncatechars:100 }}</p>
                <div class="d-flex justify-content-between align-items-center">

                    <a class="btn btn-success" href="{% url 'blog:detail' blog.pk %}" role="button">Посмотреть</a>

                    {% if perms.blog.can_change_blog and perms.blog.can_delete_blog %}
                    <a class="btn btn-warning" href="{% url 'blog:update' blog.pk %}" role="button">Редактировать</a>
                    <a class="btn btn-danger" href="{% url 'blog:delete' blog.pk %}" role="button">Удалить</a>
                    {% endif %}

                </div>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/toggle.html
{% extends 'sendler/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    {% for object in object_list %}
    <div class="card" style="width: 25rem;">
        <p class="lead">{{ object.title }}</p>
        <p></p>
        <div class="card-footer">

                {% if object.is_published %}
                <a class="btn btn-danger" href="{% url 'blog:toggle_activity' object.pk%}">Деактивировать
                    блог</a>
                {% else %}
                <a class="btn btn-success" href="{% url 'blog:toggle_activity' object.pk%}">Активировать
                    блог</a>
                {% endif %}
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}