blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity, \
    CreateBlogList
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog_list/', cache_page(60)(BlogListView.as_view()), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(),  name='detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
    path('toggle_activity', CreateBlogList, name='toggle')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sendler.urls', namespace='sendler')),
    path('contacts/', include("sendler.urls")),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sendler/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from sendler.apps import SendlerConfig
from sendler.views import IndexView, ContactsView, ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, \
    ClientDeleteView, MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    MailSettingsListView, MailSettingsDetailView, MailSettingsCreateView, MailSettingsUpdateView, \
    MailSettingsDeleteView, LogListView

app_name = SendlerConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contacts/', ContactsView.as_view(), name='contacts'),

    path('client/', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

    path('message/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('mail_settings/', cache_page(60)(MailSettingsListView.as_view()), name='mail_settings_list'),
    path('mail_settings/<int:pk>/', MailSettingsDetailView.as_view(), name='mail_settings_detail'),
    path('mail_settings/create/', MailSettingsCreateView.as_view(), name='mail_settings_create'),
    path('mail_settings/<int:pk>/update/', MailSettingsUpdateView.as_view(), name='mail_settings_update'),
    path('mail_settings/<int:pk>/delete/', MailSettingsDeleteView.as_view(), name='mail_settings_delete'),

    path('log_list/', LogListView.as_view(), name='log_list'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, ProfileView, CustomPasswordReset, UserListView, \
    UserDetailView, UserDeleteView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path("users/", UserListView.as_view(), name="user_list"),
    path("users/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("users/<int:pk>/update", UserUpdateView.as_view(), name="user_update"),
    path("users/<int:pk>/delete", UserDeleteView.as_view(), name="user_delete"),
    path('password_reset/', CustomPasswordReset.as_view(), name='password_reset')

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from blog.models import NULLABLE


class User(AbstractUser):
    """Модель пользователей"""
    username = None

    first_name = models.CharField(max_length=100, verbose_name='имя')
    email = models.EmailField(unique=True, verbose_name='email')
    phone_number = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE, help_text='введите номер телефона')
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='аватар', **NULLABLE, help_text='загрузите свой аватар')
    token = models.CharField(max_length=100, verbose_name='Token', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активный')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def __str__(self):
        return self.email

    permissions = [
        ('can_view_user', 'Может просматривать пользователей'),
        ('can_block_user', 'Может блокировать пользователей')
    ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordResetForm
from django import forms
from django.forms import ModelForm

from sendler.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Форм для регистрации пользователя"""
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    """Форма для авторизации пользователя"""
    class Meta:
        model = User
        fields = ('email', 'password')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    """Форма для редактирования профиля пользователя"""
    class Meta:
        model = User
        fields = ('first_name', 'email', 'phone_number', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserForm(StyleFormMixin, ModelForm):
    """Форма для блокировки пользователя"""
    class Meta:
        model = User
        fields = ('is_active',)


class ResetPasswordForm(StyleFormMixin, PasswordResetForm):
    """Форма для сброса пароля"""
    class Meta:
        model = User
        fields = ('email',)

users/views.py
import secrets
import random
import string

from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from users.forms import UserRegisterForm, UserLoginForm, UserProfileForm
from users.models import User
from config.settings import EMAIL_HOST_USER


class UserCreateView(CreateView):
    """Контроллер создания пользователя"""
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Привет, перейди по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )

        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class CustomPasswordReset(PasswordResetView):
    """Контроллер сброса пароля"""

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user = get_object_or_404(User, email=email)
        characters = string.ascii_letters + string.digits + string.punctuation
        new_password = ''.join(random.choice(characters) for _ in range(12))
        user.password = make_password(new_password)
        send_mail(
            subject='Вы сменили пароль',
            message=f'Ваш новый пароль {new_password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        user.save()

        return super().form_valid(form)


class UserLoginView(LoginView):
    """Контроллер логина"""
    model = User
    template_name = 'users/login.html'
    form_class = UserLoginForm
    redirect_authenticated_user = True


class ProfileView(LoginRequiredMixin, UpdateView):
    """Контроллер профиля"""
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(LoginRequiredMixin, ListView):
    """Контроллер списка пользователей"""
    model = User
    template_name = 'user_list.html'
    # permission_required = 'users.can_view_user'


class UserDetailView(LoginRequiredMixin, DetailView):
    """Контроллер пользователя"""
    model = User


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер редактирования пользователя"""
    model = User
    fields = [
        'id',
        'email',
        'is_active',
    ]
    success_url = reverse_lazy('users:user_list')


class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('users:user_list')

users/templates/users/login.html
{% extends 'sendler/base.html' %}

{% block content %}
<div class="col-8">
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}

                            <button type="submit" role="button" class="btn btn-primary" >
                                Войти
                            </button>
                            <a role="button" href="{% url 'users:password_reset' %}" class="btn btn-primary">
                        Забыли пароль?
                        </a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>


{% endblock %}

users/templates/users/password_reset.html
{% extends 'sendler/base.html' %}

{% block content %}
<div class="col-8">
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Введите email для восстановления пароля
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" role="button" class="btn btn-primary">
                            Восстановить пароль
                    </div>
                </div>
        </div>
    </div>
    </form>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'sendler/base.html' %}

{% block content %}
<div class="col-8">
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}

                            <button type="submit" role="button" class="btn btn-primary">
                              Зарегистрироваться
                            </div>
                        </div>
                    </div>
                </div>
            </form>
    </div>
</div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'sendler/base.html' %}

{% block content %}
<div class="col-8">
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Профиль
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}

                            <button type="submit" role="button" class="btn btn-primary">
                              Сохранить</button>
                             <a class="btn btn-primary" href="{% url 'sendler:index' %}" role="button">На главную</a>
                            {% if perms.sendler.can_block_user %}
                        <a class="btn btn-primary" href="{% url 'users:user_list' %}" role="button">Пользователи</a>
                        {% endif %}
                        </div>
                    </div>
                </div>
        </div>
        </form>
    </div>
</div>
</div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'sendler/base.html' %}
{% block content %}
    <a class="btn btn-primary" href="{% url 'sendler:index' %}" role="button">На главную</a>
<br>

    <div class="container">
      <h1 class="fw-light">Пользователи Email рассылок</h1>
    <hr>
        <div class="row">

            {% for object in object_list %}
                <div class="col-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h5 class="card-title">{{ object.first_name }}</h5>
                            <p class="card-text">E-mail: {{ object.email }}</p>



                            {% if not object.is_active %}
                                <p class="card-text">Заблокирован</p>
                            {% else %}
                                <p class="card-text">Активный</p>
                            {% endif %}

                            <a href="{% url 'users:user_update' object.pk %}" class="stretched-link">Подробнее</a>

                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}